### ISSUE TITLE
CloudReady and other OS support

### ISSUE THREAD

**Issue by jam7** [chromebrew/chromebrew#1151]
We would like to support not only Chromebook but also CloudReady, Chromium OS and other similar OS if it is possible and easy to do so.

There is one known problem.

 - Those OS may have it's own programs or links under `/usr/local`

For example, Chromebook itself has several programs after `dev_install` and `emerge`.  CloudReady has some from the scratch.  Chromium OS has some also...

What should we do for them?  There are several choices to how to treat those pre-existing stuff in `/usr/local`

1. Remove them all
2. Overwrite them and ignore pre-existing stuff (EDIT: `ignore` meant to remove conflicting files like `/usr/local/var` on CloudRady)
3. Use both
4. Change Chromebrew install directory to `/usr/local/.chromebrew` or something (discussed once in #536)
5. Overwrite them but don't touch `/usr/local/var` to `/var` symbolic link ( @uberhacker like this way)

Currently we use 2 or 3.  5 is kinda ugly.  It requires modifications of all programs using `/usr/local/var`.  5 may requires more modifications in future.  For example, if other OS starts creating `/usr/local/share` to `/usr/share` symbolic link, we again need to modify all programs using `/usr/local/share`.  Maybe choosing 4 is the best and safest way to avoid these problems...

Anyway, which one do you like?

**Comment by uberhacker** [comment]
I'm not in favor of 4 simply because of the fact that everything in `/usr/local/.chromebrew/bin` will need to be symlinked to `/usr/local/bin`.  Otherwise, we will need to add `/usr/local/.chromebrew/bin` as a search path in the `PATH` environment variable and this I definitely want to avoid.  I think 1 is a very bad idea.  This just might kill the base operating system functionality.  We cannot simply overwrite as suggested in 2 because in CloudReady, `/usr/local/var` is symlinked to `/var` and that is a read-only directory.  Not sure what 3 means.  Both 1 and 2?  If we implement 5, we also need to consider packages that install stuff in `/usr/local/var` and reroute those files to an alternate location.  The grabinfo package is an example of one that installs in this manner.

**Comment by lyxell** [comment]
One possible solution to 4.
After `crew install` is run:
```
for f in $(ls /usr/local/.chromebrew/bin); do
  if [ ! -f /usr/local/bin/$f ]; then
    ln  -s /usr/local/.chromebrew/bin/$f /usr/local/bin/$f
  fi
done
```

**Comment by uberhacker** [comment]
@lyxell: Nice suggestion.  How would we handle dangling symlinks once a package is removed since the symlinks are not tracked?

**Comment by lyxell** [comment]
@uberhacker 

```bash
for f in $(ls /usr/local/bin); do
  if [ ! -e $f ]; then
    rm $f
  fi
done
```

**Comment by uberhacker** [comment]
Awesome.  So then how would we handle packages that install stuff in `/usr/local/.chromebrew/include`, `/usr/local/.chromebrew/share`, `/usr/local/.chromebrew/lib(64)`, etc.?  See the can of worms this can introduce?

**Comment by lyxell** [comment]
Since we roll our own GCC, we can configure it to include those directories when compiling, if you're worried that GCC won't find libraries or headers?

**Comment by uberhacker** [comment]
Well, if it can be done elegantly, I'm all for it.  Just got to make sure we cover all the edge cases.

**Comment by jam7** [comment]
I was thinking to set PATH and LD_LIBRARY_PATH for the case of 4 like what homebrew or linuxbrew does.  Since the point of 4 is to separate namespace from pre-existing files.  Making symbolic links may cause conflicts with pre-existing files.

But yes, it's possible to make symbolic links over 4 like you guys discussed here...

**Comment by lyxell** [comment]
@jam7 That would break guest-mode, but it might be worth it, since that solution is a lot simpler. If we decide to go that path, i would suggest to add a file named .chromebrewrc or something similar, to let the only modification to .bashrc be 'source .chromebrewrc'.

**Comment by jam7** [comment]
There is PR #1182 related to this discussion.

**Comment by jam7** [comment]
Regarding to 4, there is another possible way to configure chromebrew.

Let's assume we install everything into `/usr/local/.chromebrew` for example.  We can provides following `.chromebrewrc` for the case someone want to use chromebrew from guest mode.
```
export PATH=/usr/local/.chromebrew/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/.chromebrew/lib:/usr/local/.chromebrew/lib64:$LD_LIBRARY_PATH
```
And if a user want to stick `/usr/local` instead of `/usr/local/.chromebrew`, the user can do it by simply creating single symbolic like like `ln -s /usr/local/.chromebrew /usr/local`.  With this symbolic link, even chromebrew will try to install everything into under `/usr/local/.chromebrew`, those are actually installed directly under `/usr/local`.

**Comment by minektur** [comment]
@jam7 - that works for binaries and libs, but not for stuff that chromebrew packages install in /usr/local/* where * is not bin|lib.  e.g. man pages, config files in /usr/local/etc/ etc.  The big sticking point is that cloudready effectively makes /usr/local/var unwritable (because it is a symlink to /var).  What breaks if we remove that symlink?  I have no idea.  I'm having a hard time seeing how any of these solutions is a good all-around strategy that will work with out negative side effects.  I could add an option 6) for cloudready - remount /var as writable and then install like normal - some of chromebrew's stuff will end up in /var/.... probably.  I dont like that option either though.  


I guess we could have cloudready systems have their own custom build different from other x86_64 systems - we'd have to detect it and do the right think for that platform - treat it like a different arch and in our arch-detection code special-case cloudready.

Actually - that would be another option:

7) expand our arch-detection code to treat cloud-ready as different, and specialcase the builds for that meta-arch to put things in different directories, partly.  Then also have a complete set of different binaries for cloudready.

7 at least has a chance of working without breaking stuff...

**Comment by JL2210** [comment]
How about just remove the symlink? Simple, easy, it works, and it doesn't hurt anything.

**Comment by uberhacker** [comment]
If you remove the symlink then you need to create the `/usr/local/var` directory.  We probably shouldn't be modifying the CloudReady setup but rather try workarounds instead.

**Comment by satmandu** [comment]
Chromebrew is unofficially being used on Cloudready/Flex now...

**Comment by supechicken** [comment]
@madhits Removing the `/usr/local/var` symlink should be good to go. Chromebrew should work fine on the last version of Cloudready since our prebuilt binaries are compiled on ChromeOS v90.

**Comment by madhits** [comment]
THANKS @supechicken I will do that. AWESOME to get a firm answer on what really works. So i should have no issues with cloudready after doing this? What about chromebrew installed apps? I only want to install VLC and thats it.

**Comment by supechicken** [comment]
Maybe try the following:
```bash
rm -rf /usr/local/* /usr/local/.*
```

This should wipe /usr/local entirely

**Comment by madhits** [comment]
> Maybe try the following:
> 
> ```shell
> rm -rf /usr/local/* /usr/local/.*
> ```
> 
> This should wipe /usr/local entirely

OK I ended up doing that more or less via the script, just said yes. But can you explain what pitfalls this presents? Should I put back the symbolic link after? idk Im a bit of a linux noob so any directions you can give would be great.

THANKS

**Comment by supechicken** [comment]
I have no idea on the purpose of it... But it should be fine to remove it. (if you add the symlink back it will break Chromebrew as some packages need to write into `/usr/local/var`)

**Comment by madhits** [comment]
> I have no idea on the purpose of it... But it should be fine to remove it. (if you add the symlink back it will break Chromebrew as some packages need to write into `/usr/local/var`)

Ok i only need VLC and the chrome browser on occation, so maybe its no big deal..

Thanks

**Comment by dragon788** [comment]
If you need better hardware support for Flex you should try the Brunch project with the Reven image.

**Comment by madhits** [comment]
> If you need better hardware support for Flex you should try the Brunch project with the Reven image.

I'll look at reven chromebook specs and see, I have another brunch install that I love, but this lil atom machine i never imagined it could run brunch but it is all about finding the right chrombook as a starting point for brunch.

**Comment by dragon788** [comment]
Reven is the virtual device name for Chrome OS Flex. 

https://github.com/sebanc/brunch/issues/1454#issuecomment-1152988009

If you have really old hardware you might be better served with running real Linux like Universal Blue, especially if you like an immutable system similar to how ChromeOS functions.
