### ISSUE TITLE
new doc idea....

### ISSUE THREAD

**Issue by minektur** [chromebrew/chromebrew#1307]
I'm thinking that I should write up my workflow I use when making a bunch of package updates, combination of github interface, git commands, branching, PRs etc.... 

I have a very very rough outline here:

https://gist.github.com/minektur/ad88076a179b8c6ceb12fec329506d79

I'm thinking of whipping it up into a fully-fleshed out MD to augment/replace our package build docs on the wiki....

Is this approximately what you guys do?  Do you have any feedback on the outline/process before I write up details and flesh it out...

**Comment by uberhacker** [comment]
@minektur: This is a great start.  Thank you for taking the time to put this together.  I definitely agree we need better docs.  Instead of lines 10 and 11, I would just do `git pull upstream master`.  You could start out by creating your new package in `/usr/local/lib/crew/packages` and then copy back to the main `packages` directory when you are ready to commit your changes.  You might want to mention a step after `crew install -s mycoolpackage` to examine the output of `crew files mycoolpackage` and determine if there are any library files that should be abstracted.  For instance, on a x86_64 system, you may end up with files installed in `/usr/local/lib` instead of `/usr/local/lib64`.  This would be an indicator that you need the `--libdir=#{CREW_LIB_PREFIX}` configure option.  Likewise, if you don't notice any library files, you could remove the `--libdir=...` configure option.  After this, you should probably `crew remove mycoolpackage` and make sure all the files that were installed initially are actually removed.  If you don't see any files from `crew files mycoolpackage` after installation, this is a good indicator that the install failed even if it was reported as installed successfully.  You will not likely need to git checkout specific commits.  The way I would start working on a new package is something like below:
```
$ git checkout master
$ git pull upstream master
$ git checkout -b mynewpackage
```
This will work if you don't make any local commits on your master branch.  Keep your master branch intact and updated regularly with the upstream and you should be fine.
