### ISSUE TITLE
qtbase cannot be compiled due to libressl incompatibility

### ISSUE THREAD

**Issue by vincowl** [chromebrew/chromebrew#4262]
While compiling `qtbase` to update it, errors are thrown linked to openssl messages. Google search shows that `libressl` and `qtbase` don't play together well. 4 solutions : 

1. wait for qt or libressl to handle the trouble
2. go back to `openssl` instead of `libressl`
3. create and maintain a patch which is time consuming...
4. disable ssl in qtbase compilation using flag `-no-openssl` which seems to work (qtbase is veeeery loooong to compile and still waiting for it to end while writing this)

Having a look at #3463, there was no real reason to move to libressl. Maybe solution 2 would be the best one.
FYI : `qtbase` binaries have been generated before the move to `libressl`...

**Comment by vincowl** [comment]
@uberhacker Any opinion about the previous post ? Other point, I cannot manage to install from `crew install -s` the following packages : `qtbase` followed by `qtx11extras`. `qtx11extras` doesn't install anything since it says that there is nothing to do since `QtConfig(xcb)` seems to be false.... How did you manage to build these binaries ?

**Comment by uberhacker** [comment]
Hey @vincowl: Yeah, I tried to update qt awhile back and ran into issues also.  Supposedly, libressl was forked from openssl so, in theory, it should work the same.  I know the major release update for openssl breaks EVERYTHING. LoL  I'm always hesitant to update core packages like this since so many other packages depend on it.  There is a ton of testing involved for these kinds of updates.  I'm not sure I have the energy to do it anymore. ;)

**Comment by vincowl** [comment]
@uberhacker I fully understand. That's why I suggested to set up a CI process to automatically generate all the binaries before merging a PR. This would warn us when we have packages broken by the updates. Anyway ! Could you tell me a bit more about this openssl update please ? Do you mean moving from openssl to libressl breaks everything or just the upgrade not done that led to the move to libressl ? I just need to know wether it is afterall a good idea to move to libressl or if we should move back to openssl. I will handle the upgrade if needed.

The second point related to qt compilation : we can actually compile qtbase adding the -no-openssl option. That works. What I don't get is why I can't compile qtx11extras

**Comment by ThatGeekyWeeb** [comment]
My device uses the 3.10 kernel, and has a large amount of issues with `*ssl` as a result. 
~
Compiling `openssl` (using the old package script) results in `libssl` having no start symbol, which prevents `ssl` usage.
Compiling `libressl` causes no issues, but it doesn't cooperate with my kernel, and thus anything using `ssl` breaks
~
Due to these issues, I've had to make multiple branches containing edited package scripts which avoid `ssl` at all costs.
***
I recommend using `-no-openssl` as it prevents issues with outdated kernels, although in the case that removing `ssl` support breaks certain features, `gnutls` or `mbedtls` should be used, if a option for one is available. 

~
The 3.10 kernel is still mainstream with the Acer Chromebase (code name `kitty-nyan`), this device has not reached EoL yet, and thus uses the stable version of ChromeOS, thus still being supported by Chromebrew

**Comment by ThatGeekyWeeb** [comment]
I also recommend looking at "https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5/template" as Void linux using libressl instead of openssl, and is able to compile it

**Comment by vincowl** [comment]
@ThatGeekyWeeb ok... We've just opened the Pandora's box so... Deactivating ssl in qt is not something I would promote since the best would be giving the largest amount of optionsto developers. But I hear this is a problem for you. I think we should try to update libressl (3.2 now) which may solve these troubles. Problem : when I did this, it broke my whole chromebrew install. Probably related to #4182. A huge mess....

The link you provided is interesting and it show they had to add a hack to fill libressl missing parts. I'll have a deeper look. I think I will split this problem in 2 : provide updated qt packages without ssl, and then solve the ssl trouble

**Comment by ThatGeekyWeeb** [comment]
While I have a issue with `ssl`, I've been able to avoid it using `gnutls` or `mbedtls`, although, qtbase seemingly has option to use `*tls` instead of `*ssl`.
~
And to give input on #4182 `curl` is compiled to use `openssl`, obviously this won't work, thankfully I already have a package script that uses `mbedtls` instead
> https://github.com/ThatGeekyWeeb/chromebrew/raw/openssl-repack/packages/curl.rb

**Comment by ThatGeekyWeeb** [comment]
Figured I would also give input on #4189... That's the exact commit that I now have to avoid, for some reason, these changes break the system provided curl, which prevents proper installation.
~
A proper fix would be to install curl compiled using `mbedtls` instead of libressl during installtion, before libressl, and then making sure that version of curl is used instead...

**Comment by ThatGeekyWeeb** [comment]
And, if we're going to try to compile qtbase using these patches, it would be good to implement a system that allows curl-ing multiple files.
~
Something like:
```ruby
source_files "<url1> \ <url2> \ <url3> \ <etc>"
source_sha256sum "<sum1> \ <sum2> \ <sum3> \ <etc>"
```
Idk how hard it would be to implement this, I don't really understand Ruby, and am more of a shell dude.

**Comment by uberhacker** [comment]
@vincowl: Can we close this now that qt has been updated?

**Comment by vincowl** [comment]
Not really : we removed the ssl feature from qt. We need to decide wether we upgrade libressl or if we rollback to openssl (or a third choice). Then we will be able to upgrade qt with ssl feature enabled and close this issue. Or we create a new issue for each previous step and close this one

**Comment by vincowl** [comment]
@uberhacker @cstrouse @skiman6010 What shall we do so ? Stick with libressl and upgrade it (potential troubles with qtbase while activating ssl) or go back to openssl ? I can handle the update of the package you'll choose since it will have a big impact on packages regeneration whatever the solution we'll choose.

**Comment by uberhacker** [comment]
@vincowl:  I can look into this later.  The day job is keeping me pretty busy at the moment.

**Comment by vincowl** [comment]
No problem : same here... I just wanted to exhume this one and track it later

**Comment by vincowl** [comment]
@uberhacker Any thought about libressl vs openssl ?

**Comment by uberhacker** [comment]
I think it might be worth a shot to attempt to update libressl.  There is a newer version available.

**Comment by vincowl** [comment]
Fine ! I'll have a look at its compatibility with qtbase ssl option then

**Comment by satmandu** [comment]
Did the current qtbase get compiled with openssl?

**Comment by uberhacker** [comment]
I have not tried it but we're due for a version update anyway.

**Comment by satmandu** [comment]
qtbase is at the final open source version: 5.15.2. No further updates are currently available.

I can get qttools 5.15.2 to build on armv7l, but not anything else yet...

**Comment by satmandu** [comment]
Qtbase now installs.
