### ISSUE TITLE
[swi_prolog] Failed to build

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#5224]
```
[103/106] Linking C shared library src/libswipl.so.8.2.4
[104/106] Creating library symlink src/libswipl.so.8 src/libswipl.so
[105/106] Linking C executable src/swipl
[106/106] Generating ../home/boot.prc
FAILED: home/boot.prc 
cd /usr/local/tmp/crew/swipl-8.2.4.tar.gz.dir/swipl-8.2.4/builddir/src && /usr/local/bin/cmake -E remove -f /usr/local/tmp/crew/swipl-8.2.4.tar.gz.dir/swipl-8.2.4/builddir/home/boot.prc && /usr/local/tmp/crew/swipl-8.2.4.tar.gz.dir/swipl-8.2.4/builddir/src/swipl -q -O -o /usr/local/tmp/crew/swipl-8.2.4.tar.gz.dir/swipl-8.2.4/builddir/home/boot.prc -b /usr/local/tmp/crew/swipl-8.2.4.tar.gz.dir/swipl-8.2.4/builddir/home/boot/init.pl
[FATAL ERROR: at Sun Feb 21 15:40:44 2021
        WAM Table mismatch: wam_table[8(h_mpz)] == wam_table[10(h_string)]
]
ninja: build stopped: subcommand failed.
PGO: run ninja to complete the build
ninja: error: 'man/archive', needed by 'man/lib/prologpack.tex', missing and no known rule to make it
swi_prolog failed to build: `ninja` exited with 1
```

**Comment by satmandu** [comment]
This is only an issue on armv7l. It builds fine on x86_64 & i686, at least using the package file in https://github.com/skycocker/chromebrew/pull/5109 .

**Comment by uberhacker** [comment]
Right but that PR hasn't been merged yet so it's still an issue.  Honestly, I don't think we should be removing functionality just so it compiles without errors and has a smaller footprint.  That's like saying I don't ever want to install snow tires just because it's summertime but then winter comes around and you wish you had snow tires.

**Comment by kjperkin** [comment]
I've been playing around with Prolog again, and that got me looking at this again. My original objection to the JDK was that the size and complexity of the JDK is about the same or greater than SWI-Prolog. I went to buy a pickup, and now I'm being told if I want my pickup, I also have to pay for a boat and trailer because my pickup has an optional trailer hitch. On top of that, the trailer has a design flaw that causes an intermittent electrical issue that prevents the pickup from starting if the trailer is connected (i.e. the compile error).
