### ISSUE TITLE
Sommelier does not run on AMD GPU

### ISSUE THREAD

**Issue by justinkkwan** [chromebrew/chromebrew#7483]
## Description

I installed Sommelier and Firefox then realized that Sommelier was not actually starting properly:
```
some sommelier processes failed to start
sommelier processes running:  
```

Error from log file:
```
/usr/local/bin/sommelier.elf: error while loading shared libraries: /usr/local/lib64/gbm/tls/amdgpu_gbm.so: cannot open shared object file: No such file or directory
```

## Versions and system information

***
chronos@localhost / $ crew sysinfo
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.4.206-19241-g84d38d3cc531`

- Chromebrew version: `1.26.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 85fe947 `getrealdeps: Handle patchelf inserted library paths (#7481) (10 hours ago)`

- OS variant: `Chrome OS`
- OS version: `zork-release/R105-14989.107.0`
- OS channel: `stable-channel`
***

## Additional information

Processor is the AMD Athlon™ Gold 3150C. Probably something needs to change with the [mesa package](https://github.com/chromebrew/chromebrew/blob/b5e4cedb0d3128948ce24b132f6d69fb137cedd4/packages/mesa.rb#L302) as my `/usr/local/lib64/gbm/tls/` only contains `i915_gbm.so`:
```
chronos@localhost / $ ls /usr/local/lib64/gbm/tls/
i915_gbm.so
```

**Comment by satmandu** [comment]
Here is the meson options file for mesa we are using: https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.3/meson_options.txt

Any ideas on what we would change in https://github.com/chromebrew/chromebrew/blob/b5e4cedb0d3128948ce24b132f6d69fb137cedd4/packages/mesa.rb ?

Alternately we could try to build a more recent version of mesa... 22.3 has the Angle patches for Chromium in it. That should be released in RC form at the beginning of November, 2022 as per https://docs.mesa3d.org/release-calendar.html . 

We would also need an updated linuxheaders package for the newer machines like yours, and possibly split the mesa package to be for the older and newer versions, since the newer mesa just won't run with the older kernels many chromeos machines are stuck with.

**Comment by a-hurst** [comment]
Getting the exact same issue on an ASUS Chromebook Flip CM5 (Ryzen 3250U). I tried compiling mesa myself to see if that fixed things, but that requires `linuxheaders` to be installed and that (ironically) errors out due to a missing linux header file (`linux/limits.h`, I'll make a new issue for that).

Would be great to get graphical apps up and running on this thing! I'm happy to test any potential patches/fixes.

**Comment by satmandu** [comment]
Can you also try this:
```
cd /usr/local/lib64/gbm/tls
ln -s ../../libgbm.so amdgpu_gbm.so
restartsommelier
```

**Comment by satmandu** [comment]
If that works, we can add a postinstall specific to the AMD machines to handle that.

**Comment by a-hurst** [comment]
Thanks, the `libgbm.so` symlink gets me further along! With that fixed, I hit a similar error saying that LLVM was missing, which I fixed with `crew install llvm`:

```
/usr/local/bin/sommelier.elf: error while loading shared libraries: /usr/local/lib64/libLLVM-15.so: cannot open shared object file: No such file or directory
```
Next, I got a different sort of startup error in the log complaining mostly about xkbcomp not being available, which was solved with `crew install xkbcomp`:

```
** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
sh: 1: /usr/local/bin/xkbcomp: not found
sh: 1: /usr/local/bin/xkbcomp: not found
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE)
Fatal server error:
(EE) Failed to activate virtual core keyboard: 2(EE)
```
After that, glxgears works as expected!

Thanks again for the quick help.

**Comment by satmandu** [comment]
Thanks for the follow-up!

We'll have to have add `xkbcomp` as a dependency for sommelier.

**Comment by satmandu** [comment]
And `llvm` as well...
