### ISSUE TITLE
mouse capture with sommelier

### ISSUE THREAD

**Issue by shifty-d** [chromebrew/chromebrew#7644]
i want make working mouse capturing with sommelier to use it with crouton, now in games like freedm or darkplaces(quake engine) it now working, any idea to fix?

**Comment by supechicken** [comment]
Open a new issue in crouton repo?

**Comment by satmandu** [comment]
I don't think that sommelier supports mouse capture unless the app is Fullscreen.

**Comment by foss-dragon** [comment]
> I don't think that sommelier supports mouse capture unless the app is Fullscreen.

then how sommelier do it in crostini?

**Comment by foss-dragon** [comment]
> Open a new issue in crouton repo?

nobody give me information about that in crouton repo

**Comment by satmandu** [comment]
> > I don't think that sommelier supports mouse capture unless the app is Fullscreen.
> 
> then how sommelier do it in crostini?

If you do a `crew install xorg_xeyes ; xeyes` and you move the mouse over the xeyes, you will see that mouse capture works when the mouse is over the app.

**Comment by foss-dragon** [comment]
> > > I don't think that sommelier supports mouse capture unless the app is Fullscreen.
> > 
> > 
> > then how sommelier do it in crostini?
> 
> If you do a `crew install xorg_xeyes ; xeyes` and you move the mouse over the xeyes, you will see that mouse capture works when the mouse is over the app.

i want that it games, not in xeyes)

**Comment by satmandu** [comment]
Does the mouse not work in games when Fullscreen?

**Comment by foss-dragon** [comment]
> Does the mouse not work in games when Fullscreen?

yes, fullscreen not working too, cursor still can go below to the panel and trigger it to open, as example. once again, crostini probably uses newer version of sommelier, so i think it can capture mouse

**Comment by satmandu** [comment]
Try it with the new sommelier to see if it is fixed?

```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=sommelier_new CREW_TESTING=1 crew update
crew upgrade
```

**Comment by foss-dragon** [comment]
> Try it with the new sommelier to see if it is fixed?
> 
> ```
> CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=sommelier_new CREW_TESTING=1 crew update
> crew upgrade
> ```

don't working (

**Comment by satmandu** [comment]
OK there's a slightly newer version of sommelier now... but if it doesn't work with that, after a `crew update ; crew upgrade`, then this is an upstream problem... which maybe you can help debug?

**Comment by foss-dragon** [comment]
> OK there's a slightly newer version of sommelier now... but if it doesn't work with that, after a `crew update ; crew upgrade`, then this is an upstream problem... which maybe you can help debug?

tell me anything, i want latest sommelier with mouse capture, how i can help to achieve it?

**Comment by satmandu** [comment]
Looking at this: https://bugs.chromium.org/p/chromium/issues/detail?id=927521

Is `chrome://flags#exo-pointer-lock` set for you?

**Comment by satmandu** [comment]
Also maybe this is useful?

`chrome://flags/#exo-lock-notification`

**Comment by foss-dragon** [comment]
> Looking at this: https://bugs.chromium.org/p/chromium/issues/detail?id=927521
> 
> Is `chrome://flags#exo-pointer-lock` set for you?

this flag doesn't exist anymore in v107

**Comment by satmandu** [comment]
> > Looking at this: https://bugs.chromium.org/p/chromium/issues/detail?id=927521
> > Is `chrome://flags#exo-pointer-lock` set for you?
> 
> this flag doesn't exist anymore in v107

Agreed. This is still there: `chrome://flags/#exo-lock-notification`

**Comment by foss-dragon** [comment]
> > > Looking at this: https://bugs.chromium.org/p/chromium/issues/detail?id=927521
> > > Is `chrome://flags#exo-pointer-lock` set for you?
> > 
> > 
> > this flag doesn't exist anymore in v107
> 
> Agreed. This is still there: `chrome://flags/#exo-lock-notification`

it's not working too, idk why

**Comment by foss-dragon** [comment]
i installed crostini, so, in crostini works, in crouton with new sommelier with chromebrew, no, all flags enabled like said above

**Comment by satmandu** [comment]
Maybe @supechicken has some idea...

**Comment by foss-dragon** [comment]
so, i still trying everything, and noticed a funny thing, i removed sommelier from crew/crouton/etc, and got freedoom for example working without sommelier but looking like with it, can someone explain that?

**Comment by foss-dragon** [comment]
@supechicken @satmandu guys if you have telegram please find me @bluebird_sh i want talk with y'all about this sommelier issue, maybe we can fix it

**Comment by satmandu** [comment]
> so, i still trying everything, and noticed a funny thing, i removed sommelier from crew/crouton/etc, and got freedoom for example working without sommelier but looking like with it, can someone explain that? pointer lock still don't work btw

Wayland apps work without sommelier, as last ng as apps only need an older Wayland server.

**Comment by foss-dragon** [comment]
> > so, i still trying everything, and noticed a funny thing, i removed sommelier from crew/crouton/etc, and got freedoom for example working without sommelier but looking like with it, can someone explain that? pointer lock still don't work btw
> 
> Wayland apps work without sommelier, as last ng as apps only need an older Wayland server.

i see you commit yesterday with updated sommelier, is there any changes with pointer lock issue?

**Comment by foss-dragon** [comment]
> > so, i still trying everything, and noticed a funny thing, i removed sommelier from crew/crouton/etc, and got freedoom for example working without sommelier but looking like with it, can someone explain that? pointer lock still don't work btw
> 
> Wayland apps work without sommelier, as last ng as apps only need an older Wayland server.

if that true, why pointer lock still unavailable? xwayland/wayland restrictions?

**Comment by foss-dragon** [comment]
UPD: i started sommelier binary from latest chromebrew package in crostini, and problem with the pointer lock exists somehow

**Comment by satmandu** [comment]
I don't know where to go from here. You will have to open a discussion upstream or help debug the code yourself.

This is way outside my wheelhouse...

**Comment by foss-dragon** [comment]
> 

how i can debug it?

**Comment by foss-dragon** [comment]
i take sommelier source to github, if someone interested, it's in my profile

**Comment by supechicken** [comment]
@satmandu This might be a security restriction that blocks "untrusted" applications (refer to https://github.com/dnschneid/crouton/issues/4814)

**Comment by iamda-y** [comment]
@halt-spesn 
@satmandu 
@supechicken 
@Zopolis4 
@VenomousSteam81
@myelin

From my recent analysis of the chromium codebase and tracing the exact call chain:

In theory:
The format for Exo to classify a window as ARC is "org.chromium.arc.%d". 
We would set a Wayland app_id and that would simply make CanLockPointer true; one sommelier flag can force it globally. 
This is because ExoAppTypeResolver gets registered during Chrome startup and runs for any Wayland client on wayland-0, so that format literally classifies as an ARC window as far as I can tell. So for mouse capture sommelier can literally set this via --application-id or the app itself can set it via xdg_toplevel.set_app_id() 

My entire research chain was empirically confirmed:

<img width="899" height="52" alt="Image" src="https://github.com/user-attachments/assets/36e49196-a319-488a-a2b7-e68701f3789f" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8c63f379-e745-4ff8-aab4-1b47463fae25" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2a2a8eda-5cd3-42ad-b46d-5050afb83236" />

<img width="855" height="131" alt="Image" src="https://github.com/user-attachments/assets/df108a45-f377-431b-9e3d-48f5308c587b" />

<img width="1004" height="866" alt="Image" src="https://github.com/user-attachments/assets/bc41fcf3-3fd3-4b3a-b20a-7d6f0c49b34b" />

<img width="825" height="563" alt="Image" src="https://github.com/user-attachments/assets/ff16d900-1151-4064-99d4-14e113a7cb4a" />

<img width="741" height="577" alt="Image" src="https://github.com/user-attachments/assets/0def337d-e599-4dd1-a248-e53bc6baa37a" />

<img width="752" height="121" alt="Image" src="https://github.com/user-attachments/assets/645df735-f535-4adf-82af-86b72f7c0dc3" />

<img width="1361" height="374" alt="Image" src="https://github.com/user-attachments/assets/253b7cb4-1860-4aa3-816d-511497313d99" />

<img width="1687" height="736" alt="Image" src="https://github.com/user-attachments/assets/dd1344fa-3766-4a32-bd75-bb1076a08698" />

**Comment by VenomousSteam81** [comment]
Neat! I don't know why you mentioned me, but very cool!

**Comment by shadowed1** [comment]
Thanks to @iamda-y for showing me the way. Patching sommelier to enable icon support with right clicking is possible while preserving mouse capture/lock. We can have our cake and eat it too :)
