### ISSUE TITLE
please add brew-bios and snapd

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9564]
please add systemd(detected dep) , brew-bios, and snapd

**Comment by uberhacker** [comment]
systemd is a difficult ask because it requires full control over the system.  Google locks down the "operating system" directories to be read-only.  Unless the system is fully rooted, this is not possible.  snapd is just another package management app which basically does the same thing as this project so that is not really practical.  Not sure about brew-bios.  Do you have a link to a project?

**Comment by yeesterPlus** [comment]
make brew bios please

**Comment by yeesterPlus** [comment]
and please scan the /usr/bin folder for systemd

**Comment by uberhacker** [comment]
Your replies are not making sense.
